#ifndef CONVENTION_H
#define CONVENTION_H
typedef enum
{
    OP_SUCCESS,
    OP_ERROR,
    OP_ERROR_INVALID_ARG,
    OP_ERROR_INVALID_INPUT,
    OP_ERROR_NEGATIVE_POSITION,
    OP_ERROR_OUT_OF_RANGE_POSITION,
    OP_ERROR_KEY_NOT_FOUND,
    OP_ERROR_EMPTY_LIST,
    OP_SINGLE_NODE_LIST,
    OP_KEY_AT_HEAD,
    OP_ALLOC_FAILED
} opStatus;
#endif